import { test, expect } from '@playwright/test';
import SF from './sfdx';

// Patch for https://github.com/oven-sh/bun/issues/2081; Credit: https://github.com/Electroid
process.stdout.getWindowSize = () => [80, 80];
process.stderr.getWindowSize = () => [80, 80];

const alias = process.env.ORG_ALIAS || '';
const backupContactEmail = process.env.BACKUP_CONTACT_EMAIL || '';
const backupContactName = process.env.BACKUP_CONTACT_NAME || '';
const backupContactNumber = process.env.BACKUP_CONTACT_NUMBER || '';
const home = process.env.PARTNER_PORTAL_PAGE || '';
const listingSecurityReviewUrl = 'https://partners.salesforce.com/listingSecurityReview?listingId=' + (process.env.APPEXCHANGE_LISTING_ID || '');
const listingId = process.env.APPEXCHANGE_LISTING_ID || '';
const marketplaceId = process.env.APPEXCHANGE_MKTP_ID || '';
const primaryContactEmail = process.env.PRIMARY_CONTACT_EMAIL || '';
const primaryContactName = process.env.PRIMARY_CONTACT_NAME || '';
const primaryContactNumber = process.env.PRIMARY_CONTACT_NUMBER || '';
const sfPlatformTechDetails = process.env.SALESFORCE_PLATFORM_TECHNICAL_DETAILS || '';
const technicalDescription = process.env.TECHNICAL_DESCRIPTION || '';
const versionId = process.env.PACKAGE_VERSION_ID || '';
const wizardForSecReviewLink = 'https://partners.salesforce.com/listingSecurityReview?listingId=' +  listingId + '&mktp=' + marketplaceId + '&packageVerId=' + versionId + '&step=1';

test('Automate Security Review', async ({ page }) => {
  const sf = await SF.retrieveOrgInfo(alias);
  await page.goto(sf.frontdoorUrl);
  await page.goto(home);
  await page.getByRole('banner', { name: 'Header' }).getByRole('button', { name: 'Log In' }).click();
  await page.locator('c-pc-login-tbid').getByRole('button', { name: 'Log in' }).click();
  await page.getByRole('button', { name: 'Salesforce' }).click();
  await page.waitForLoadState('networkidle');
  await page.goto(page.url().replace('https://login.salesforce.com',sf.instanceUrl).replace('&sdtd=1',''));
  await page.getByRole('menuitem', { name: 'Publishing' }).click();
  await page.getByRole('link', { name: 'Packages' }).click();
  await page.waitForLoadState('networkidle');
  await page.goto(wizardForSecReviewLink);
  await page.locator('[id=\'ListingSecurityReview:PartnerCommunityLayout:mainpage:j_id619:j_id620:srContactInfo:srContactName\']').fill(primaryContactName);
  await page.locator('[id=\'ListingSecurityReview:PartnerCommunityLayout:mainpage:j_id619:j_id620:srContactInfo:srContactEmail\']').fill(primaryContactEmail);
  await page.locator('[id=\'ListingSecurityReview:PartnerCommunityLayout:mainpage:j_id619:j_id620:srContactInfo:srContactPhone\']').fill(primaryContactNumber);
  await page.locator('[id=\'ListingSecurityReview:PartnerCommunityLayout:mainpage:j_id619:j_id620:srContactInfo:srSecContactName\']').fill(backupContactName);
  await page.locator('[id=\'ListingSecurityReview:PartnerCommunityLayout:mainpage:j_id619:j_id620:srContactInfo:srSecContactEmail\']').fill(backupContactEmail);
  await page.locator('[id=\'ListingSecurityReview:PartnerCommunityLayout:mainpage:j_id619:j_id620:srContactInfo:srSecContactPhone\']').fill(backupContactNumber);
  await page.getByRole('button', { name: 'Save & Next' }).click();
  await page.locator('[id=\'ListingSecurityReview:PartnerCommunityLayout:mainpage:j_id664:j_id665:j_id667:j_id673:0:j_id677:0:inputCheckbox\']').setChecked(true);
  await page.locator('[id=\'ListingSecurityReview:PartnerCommunityLayout:mainpage:j_id664:j_id665:j_id667:j_id673:1:j_id677:0:inputCheckbox\']').setChecked(true);
  await page.locator('[id=\'ListingSecurityReview:PartnerCommunityLayout:mainpage:j_id664:j_id665:j_id667:j_id673:2:j_id677:0:j_id706:0\']').setChecked(true);
  await page.locator('[id=\'ListingSecurityReview:PartnerCommunityLayout:mainpage:j_id664:j_id665:j_id667:j_id673:2:j_id677:1:inputCheckbox\']').setChecked(true);
  await page.locator('[id=\'ListingSecurityReview:PartnerCommunityLayout:mainpage:j_id664:j_id665:j_id667:j_id673:3:j_id677:0:inputCheckbox\']').setChecked(true);
  await page.locator('[id=\'ListingSecurityReview:PartnerCommunityLayout:mainpage:j_id664:j_id665:j_id667:j_id673:3:j_id677:1:inputCheckbox\']').setChecked(true);
  await page.locator('[id=\'ListingSecurityReview:PartnerCommunityLayout:mainpage:j_id664:j_id665:j_id667:j_id673:3:j_id677:2:inputCheckbox\']').setChecked(true);
  await page.locator('[id=\'ListingSecurityReview:PartnerCommunityLayout:mainpage:j_id664:j_id665:j_id667:j_id673:3:j_id677:3:inputCheckbox\']').setChecked(true);
  await page.locator('[id=\'ListingSecurityReview:PartnerCommunityLayout:mainpage:j_id664:j_id665:j_id667:j_id673:3:j_id677:4:j_id699:1\']').setChecked(true);
  await page.getByRole('button', { name: 'Save & Next' }).click();
  await page.locator('[name=\'ListingSecurityReview:PartnerCommunityLayout:mainpage:j_id722:j_id723:j_id724:j_id732:0:j_id751\']').fill(technicalDescription);
  await page.locator('[id=\'ListingSecurityReview:PartnerCommunityLayout:mainpage:j_id722:j_id723:j_id724:j_id732:1:inputCheckbox\']').setChecked(true);
  await page.locator('[id=\'ListingSecurityReview:PartnerCommunityLayout:mainpage:j_id722:j_id723:j_id724:j_id732:2:inputCheckbox\']').setChecked(true);
  await page.locator('[id=\'ListingSecurityReview:PartnerCommunityLayout:mainpage:j_id722:j_id723:j_id724:j_id732:3:inputCheckbox\']').setChecked(true);
  await page.locator('[id=\'ListingSecurityReview:PartnerCommunityLayout:mainpage:j_id722:j_id723:j_id724:j_id732:4:j_id754:1\']').setChecked(true);
  await page.locator('[name=\'ListingSecurityReview:PartnerCommunityLayout:mainpage:j_id722:j_id723:j_id724:j_id732:5:j_id751\']').fill(sfPlatformTechDetails);  
  await page.locator('[id=\'ListingSecurityReview:PartnerCommunityLayout:mainpage:j_id722:j_id723:j_id724:j_id732:6:inputCheckbox\']').setChecked(true);
  await page.locator('[id=\'ListingSecurityReview:PartnerCommunityLayout:mainpage:j_id722:j_id723:j_id724:j_id732:7:inputCheckbox\']').setChecked(true);
  await page.locator('[id=\'ListingSecurityReview:PartnerCommunityLayout:mainpage:j_id722:j_id723:j_id724:j_id732:8:j_id754:1\']').setChecked(true);
  await page.locator('[id=\'ListingSecurityReview:PartnerCommunityLayout:mainpage:j_id722:j_id723:j_id724:j_id732:9:inputCheckbox\']').setChecked(true);
  await page.locator('[id=\'ListingSecurityReview:PartnerCommunityLayout:mainpage:j_id722:j_id723:j_id724:j_id732:10:inputCheckbox\']').setChecked(true);
  await page.locator('[id=\'ListingSecurityReview:PartnerCommunityLayout:mainpage:j_id722:j_id723:j_id724:j_id732:11:inputCheckbox\']').setChecked(true);
  await page.getByRole('button', { name: 'Save & Next' }).click();
  await page.getByRole('button', { name: 'Save & Next' }).click();
  await page.locator('[id=\'webapp_NA_checkbox\']').setChecked(true);
  await page.locator('[id=\'client_NA_checkbox\']').setChecked(true);
  await page.locator('[id=\'mobile_NA_checkbox\']').setChecked(true);
  await page.getByRole('button', { name: 'Save & Next' }).click();
  await page.getByRole('button', { name: 'Save & Next' }).click();
  await page.getByRole('button', { name: 'Submit' }).click();
  await expect(page).toHaveURL(new RegExp('^' + listingSecurityReviewUrl.replace('?','\\?')));
});